# Generated by Django 5.2 on 2025-04-16 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PatientManagement', '0001_initial'),
        ('UserRoleManagement', '0005_rename_role_userorganizations_role_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientVitals',
            fields=[
                ('vital_id', models.AutoField(primary_key=True, serialize=False)),
                ('logged_at', models.DateTimeField()),
                ('blood_pressure', models.CharField(max_length=20)),
                ('heart_rate', models.IntegerField()),
                ('temperature', models.DecimalField(decimal_places=1, max_digits=4)),
                ('respiratory_rate', models.IntegerField()),
                ('oxygen_saturation', models.DecimalField(decimal_places=1, max_digits=4)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('height', models.DecimalField(decimal_places=2, max_digits=5)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization_id', models.ForeignKey(db_column='organization_id', on_delete=django.db.models.deletion.CASCADE, to='UserRoleManagement.organizations')),
                ('patient_id', models.ForeignKey(db_column='patient_id', on_delete=django.db.models.deletion.CASCADE, to='PatientManagement.patients')),
            ],
        ),
    ]
