# Generated by Django 5.2 on 2025-04-17 19:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PatientManagement', '0004_patienthistory'),
        ('UserRoleManagement', '0005_rename_role_userorganizations_role_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientDocuments',
            fields=[
                ('document_id', models.AutoField(primary_key=True, serialize=False)),
                ('document_type', models.CharField(max_length=50)),
                ('file_name', models.CharField(max_length=255)),
                ('file_path', models.CharField(max_length=500)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('organization_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserRoleManagement.organizations')),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PatientManagement.patients')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='UserRoleManagement.users')),
                ('visit_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PatientManagement.patienthistory')),
            ],
        ),
    ]
