# Generated by Django 5.2 on 2025-04-17 19:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PatientManagement', '0005_patientdocuments'),
        ('UserRoleManagement', '0005_rename_role_userorganizations_role_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescriptions',
            fields=[
                ('prescription_id', models.AutoField(primary_key=True, serialize=False)),
                ('follow_up_needed', models.BooleanField(default=False)),
                ('follow_up_date', models.DateField(blank=True, null=True)),
                ('test_required', models.BooleanField(default=False)),
                ('test_details', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescribed_by', to='UserRoleManagement.users')),
                ('organization_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserRoleManagement.organizations')),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PatientManagement.patients')),
                ('tenant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserRoleManagement.tenant')),
                ('visit_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PatientManagement.patienthistory')),
            ],
        ),
    ]
