# Generated by Django 5.2 on 2025-04-17 19:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PatientManagement', '0006_prescriptions'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrescriptionMedicines',
            fields=[
                ('medicine_id', models.AutoField(primary_key=True, serialize=False)),
                ('medicine_name', models.CharField(max_length=255)),
                ('dosage', models.CharField(max_length=50)),
                ('frequency', models.CharField(max_length=50)),
                ('duration_days', models.IntegerField()),
                ('additional_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('prescription_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicines', to='PatientManagement.prescriptions')),
            ],
        ),
    ]
