# Generated by Django 5.2 on 2025-04-19 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PatientManagement', '0007_prescriptionmedicines'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescriptions',
            name='doctor_id',
        ),
        migrations.RemoveField(
            model_name='prescriptions',
            name='organization_id',
        ),
        migrations.RemoveField(
            model_name='prescriptions',
            name='patient_id',
        ),
        migrations.RemoveField(
            model_name='prescriptions',
            name='tenant_id',
        ),
        migrations.RemoveField(
            model_name='prescriptions',
            name='visit_id',
        ),
        migrations.DeleteModel(
            name='PrescriptionMedicines',
        ),
        migrations.DeleteModel(
            name='Prescriptions',
        ),
    ]
