# Generated by Django 5.2 on 2025-04-30 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PatientManagement', '0008_remove_prescriptions_doctor_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patientvitals',
            old_name='organization_id',
            new_name='organization',
        ),
        migrations.RenameField(
            model_name='patientvitals',
            old_name='patient_id',
            new_name='patient',
        ),
    ]
