# Generated by Django 5.2 on 2025-04-19 10:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('PatientManagement', '0008_remove_prescriptions_doctor_id_and_more'),
        ('UserRoleManagement', '0005_rename_role_userorganizations_role_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescriptions',
            fields=[
                ('prescription_id', models.AutoField(primary_key=True, serialize=False)),
                ('follow_up_needed', models.BooleanField(default=False)),
                ('follow_up_date', models.DateField(blank=True, null=True)),
                ('test_required', models.BooleanField(default=False)),
                ('test_details', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescribed_by', to='UserRoleManagement.users')),
                ('organization_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserRoleManagement.organizations')),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PatientManagement.patients')),
                ('tenant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserRoleManagement.tenant')),
                ('visit_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PatientManagement.patienthistory')),
            ],
        ),
        migrations.CreateModel(
            name='PrescriptionMedicines',
            fields=[
                ('medicine_id', models.AutoField(primary_key=True, serialize=False)),
                ('medicine_name', models.CharField(max_length=255)),
                ('dosage', models.CharField(max_length=50)),
                ('frequency', models.CharField(max_length=50)),
                ('duration_days', models.IntegerField()),
                ('additional_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('prescription_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicines', to='PharmacyManagement.prescriptions')),
            ],
        ),
    ]
