# Generated by Django 5.2 on 2025-04-19 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('PatientManagement', '0008_remove_prescriptions_doctor_id_and_more'),
        ('PharmacyManagement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicationSchedules',
            fields=[
                ('schedule_id', models.AutoField(primary_key=True, serialize=False)),
                ('dose_count', models.IntegerField()),
                ('dose_taken', models.IntegerField(default=0)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('frequency', models.CharField(choices=[('hourly', 'Hourly'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('custom', 'Custom')], max_length=10)),
                ('interval_hours', models.IntegerField(blank=True, null=True)),
                ('days_gap', models.IntegerField(blank=True, null=True)),
                ('preferred_times', models.JSONField()),
                ('timezone', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('stopped', 'Stopped')], max_length=10)),
                ('next_dose_at', models.DateTimeField()),
                ('medicine_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PharmacyManagement.prescriptionmedicines')),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PatientManagement.patients')),
                ('prescription_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PharmacyManagement.prescriptions')),
            ],
        ),
    ]
