# Generated by Django 5.2 on 2025-04-16 09:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserRoleManagement', '0002_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organizations',
            fields=[
                ('organization_id', models.AutoField(primary_key=True, serialize=False)),
                ('org_type', models.CharField(max_length=100)),
                ('org_name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=500)),
                ('contact_info', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, to='UserRoleManagement.tenant')),
            ],
        ),
    ]
