# Generated by Django 5.2 on 2025-04-16 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserRoleManagement', '0004_userroles_userorganizations'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userorganizations',
            old_name='role',
            new_name='role_id',
        ),
    ]
